### ISSUE TITLE
Improve Sunstone load times

### ISSUE THREAD

**Issue by abelCoronado93** [OpenNebula/one#1495]
## Version of OpenNebula
- [ ] 5.2.2
- [ ] 5.4.0
- [ ] 5.4.1
- [ ] 5.4.2
- [ ] 5.4.3
- [X] Development build

## Component
- [ ] Authorization (LDAP, x509 certs...)
- [ ] Command Line Interface (CLI)
- [ ] Contextualization
- [ ] Documentation
- [ ] KVM
- [ ] Networking
- [ ] Orchestration (OpenNebula Flow)
- [X] Sunstone
- [ ] Storage
- [ ] Scheculer
- [ ] vCenter

## Description
Improve the Sunstone accounting times and VMs caching

## Tasks
- [x] VMs caching
- [x] Minimize overhead in Sinatra
- [ ] Optimize XML parser

**Comment by rsmontero** [comment]
Some related developments are being tracked in other issues (advanced options for XML parser to speed-up to_json and a redesigned dashboard)
