### ISSUE TITLE
[vCenter] Improve TM Disk storage

### ISSUE THREAD

**Issue by Semedi** [OpenNebula/one#2171]
This is going to be a major feature, we take advance of this issue to keep track of the whole vCenter tm development.

# Enhancement Request
### Problems and work:

* make better code
* arrange TM
* Fix 2 complex features: 
    * save as (working as expected)
    * instantiate to persistent (it has problems)
* **File System problems**:

    OpenNebula copy the images inside template folder.
    This can lead into some problems, is not the best place to store the disk.

    Would be better to copy the disk in other folder like one default folder (root) or wait for the creation of 
    the creation of the new VM folder (not sure if possible). 

## Use cases

(example) try to update a template with a new disk  and then perform the instantiate, opennebula will copy the disk inside vCenter Template's folder.

## Ideas

copy the same FS architecture of OpenNebula:
* folder with datastore id
* differencie between normal, volatile images...

# Progress Status

### development road
- [x] [TM Code Refactor](https://github.com/OpenNebula/one/issues/2387)
- [x] [Save as Refactor](https://github.com/OpenNebula/one/issues/2386)
- [x] [Instantiate as persistent Refactor](https://github.com/OpenNebula/one/issues/1762)
- [x] Feature, vCenter storage new folders

#### Related issues:
#1350 #1540 #2335

**Comment by ccesario** [comment]
We are facing some problems due it. 
As described by @Semedi the images (VMDK) are stored outside from root VM directory. 
We have some internal procedures that copy "root VM" directory using filesystem (ESXI host) that present error due  the VMDK disk are in other folder.

**Comment by ccesario** [comment]
One more bit comment.
I think that is not needed a root folder to create a VM, this can be optional. 
It would better keep the VM folder in **root /** directory in Datastore  as vCenter do, or make this optional.

With this when any action needed to be done by vCenter, it is more clear to identify the VM folders, the relationship between VM and his folder.

(Backups, Storage vMotion)

**Comment by tinova** [comment]
Management of OpenNebula managed disks. All disks copied by ONE will be within a 'one' (this can be configurable) folder:

 | one | <id_images_ds> | hash.vmdk
          | <id_system_ds> | <vid> | <vid-disk>.vmdk

**Comment by tinova** [comment]
Image and disk location management to be treated in #2762
