### ISSUE TITLE
PostgreSQL Support

### ISSUE THREAD

**Issue by vholer** [OpenNebula/one#3600]
**Description**

OpenNebula uses MySQL and SQLite as DB backends to persist state. State is managed through basic SQL queries. The goal is to implement a new backend for the OpenNebula based on PostgreSQL. This is a tracking issue for the student's bachelor project.

**Milestones**

- Implementation SQL backend based on PostgreSQL
- Update user-land tools that interface the DB directly
- Simple document on how to configure/use PostgreSQL with OpenNebula.

## Progress Status
- [x] Branch created 
- [x] Code committed to development branch
- [x] Testing - QA
- [x] Documentation 
- [x] Release notes - resolved issues, compatibility, known issues
- [x] Code committed to upstream release/hotfix branches
- [x] Documentation committed to upstream release/hotfix branches

**Comment by vholer** [comment]
New database backend support is merged and documented. Closing.
