### ISSUE TITLE
Fireedge Self Service Portal

### ISSUE THREAD

**Issue by jloboescalona2** [OpenNebula/one#3951]
**Description**

Create a self service portal backend for OpenNebula & Edge platforms - Fireedge.

**Use case**

New interface based on React to define and consume services in local premises or edge location

**TODO**

- [ ] Check that fireedge can run on a separate server

## Progress Status
- [ ] Branch created 
- [ ] Code committed to development branch
- [ ] Testing - QA
- [ ] Documentation 
- [ ] Release notes - resolved issues, compatibility, known issues
- [ ] Code committed to upstream release/hotfix branches
- [ ] Documentation committed to upstream release/hotfix branches

**Comment by carloshm91** [comment]
Excellent! I look forward to the updates.

**Comment by tinova** [comment]
will be addressed as part of #5422
