### ISSUE TITLE
Prepare Sunstone for Modular Development

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5623]
**Description**

In order to parallelise Sunstone React (#5422 ) development we need:

- [x] Fully functional tab to use as example (VM & VM Template) (#5637)
- [x] Set of tests covering the example tab (#5626)
- [x] Development guide that covers the main components of the front-end (#5630)
- [x] Start outsourcing with host tab
   - [x] Our Work - Prepare boilerplate
      - [x] Redux API - Host actions
      - [x] Prepare yaml
      - [x] [TINO] Prepare VM with compiled FireEdge/Sunstone and Old Sunstone
   - [x] Their Work
      - [ ] 4 bulk actions (select cluster - with dialog, enable, disable, offline)
      - [ ] 4 info tabs (VMs, Wilds, Zombies, NUMA)
      - [ ] creation diaogs for all hypervisors except vCenter

**Comment by sbbarragan** [comment]
PRs to merge:
- https://github.com/OpenNebula/one-ee/pull/1711
- https://github.com/OpenNebula/one-ee/pull/1712

**Comment by tinova** [comment]
to be completed by #5755
