### ISSUE TITLE
Improve database search queries and performance (JSON)

### ISSUE THREAD

**Issue by al3xhh** [OpenNebula/one#5861]
**Description**
Currently there are FTS searches that allow users to search by the values that are in the VM template. The idea is to change this searches to start using JSON searches in order to improve the performance of the database and the quality of the queries.

**Use case**
Improve the searches that can be performed against the database, this will be very useful for the new Sunstone. Also the performance of the database will be much better.

**Interface Changes**
The changes will be mainly in the OpenNebula core, the API will remain the same. Also a migrator will be needed to remove the current `search_token` column and replace it by the `json_body` one.

**Tasks**

- [x] Add info to compatibility guide (how long the migrator, changes in DB)
- [x] Scalability tests DB in repo
- [x] Extend search.rb test
- [x] [Add info on how to use the DB in one-infra wiki](https://opennebula.slack.com/archives/C03F53WFN5R/p1655213274688629)
- [x] [Add documentation](https://docs.opennebula.io/6.99/management_and_operations/vm_management/vm_instances.html#searching-for-vm-instances)
- [x] Add to What's New

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
branch "https://github.com/OpenNebula/one-ee/tree/fireedge-f-5861" and "https://github.com/OpenNebula/one-ee/tree/f-5861"
