### ISSUE TITLE
Extended Quotas Support in WHMCS

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5863]
**Description**

The following quotas are missing:

- [x] Quotas/Metric Billing for Disk Usage on a Per Datastore basis
- [x] Quotas/Metric Billing for Networking Usage
- [x] Quotas for the remaining stats if necessary (VMs, Running Resources)

**Tasks**
- [x] Add whmcs module to one-ee-repo
- [x] Check that it packages correctly
- [x] Test it with a scratch WHMCS and ONE isntall
- [x] Need to add documentation about new features in WHMCS guide
- [x] Add to resolved issues, as feature, with link to documentation

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by onenhansen** [comment]
* code https://github.com/OpenNebula/one-ee-tools/pull/39
* docs https://github.com/OpenNebula/docs/pull/2372
* docs https://github.com/OpenNebula/docs/pull/2376
