### ISSUE TITLE
Review Keyboard Functionality in Guacamole VNC/RDP/SSH

### ISSUE THREAD

**Issue by FrederickBor** [OpenNebula/one#5897]
**Description**

Evaluate keyboard use for Sunstone VM console access

**Tasks**

- [x] Change keymap input to a selector. it would be good if available keymap values for remote connections were displayed in a selector instead of having to write them as this could lead to errors. When users misspell the keymap value, the VMs are not getting instantiated.
- [x] Check non-US keyboard in Guacamole RDP
- [x]  Check non-US keyboard in Guacamole SSH

Related to #5766

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by FrederickBor** [comment]
PR to be approved:
- https://github.com/OpenNebula/one-ee/pull/2234

**Comment by FrederickBor** [comment]
Docs: https://github.com/OpenNebula/docs/pull/2362
