### ISSUE TITLE
[Sunstone] Virtual Routers Instances & Templates Tab

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5899]
**Description**

Redesign and implement Virtual Routers Instances & Templates in FireEdge Sunstone.

Related to #5422

**Tasks**

- [ ] Add parameters from #6441 
- [ ] Don't allow attach nics as alias as it is not supported by the core.
![VR Alias](https://github.com/OpenNebula/one/assets/5102/dd41f862-068c-4dbe-be09-113c2c387a3f)
- [ ] [Implement floating IP](https://github.com/OpenNebula/one/issues/6441)

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by rsmontero** [comment]
Add parameters from #6441

**Comment by vichansson** [comment]
Missing separate one-6.8 PR (code + docs)
