### ISSUE TITLE
[Sunstone] Implement Support Tab

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5905]
**Description**

Implement Zendesk Support Tab integration.

- [x] evaluate create a ticket modal from any datatable
- [x] Add option to upload files
- [x] make sure failed login attempts are logged in fireedge.log

Related to #5422

**Tasks**

## Progress Status
- [x] Code committed
- [x] Testing - QA
- [x] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
- [ ] evaluate create a ticket modal from any datatable
