### ISSUE TITLE
[Sunstone] Support tab

### ISSUE THREAD

**Issue by tinova** [OpenNebula/one#5924]
**Description**

Implement zendesk integration

**Tasks**

- [ ] mimic Ruby Sunstone functionality
- [ ] evaluate create a ticket modal from any datatable

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by tinova** [comment]
duplicated by #5905
