### ISSUE TITLE
Backup Jobs

### ISSUE THREAD

**Issue by rsmontero** [OpenNebula/one#6063]
**Description**
Dealing with a high number of VMs that require backup can be cumbersome, as it needs to be defined one by one. This feature it to ease this process by defining backup jobs. A backup job should let you:

* Define the VMs will be part of the backup
* Define an order to perform the backups of the VMs in the job
* Define a backup policy for the job (i.e. type, schedule etc...)
* Define backup parameters like KEEP_LAST target datastore

**Use case**
Simplify operations for medium/large VM backup pools

**Interface Changes**
This feature will probably need to introduce the backup job as an entity or extend the VMGroup abstraction (TBD)

**Tasks**
- [x] Backup Job Resource
- [x] Scheduled Action Manager handles Backup Job execution
- [x] Scheduled Action Resource
  - [x] Handle Backup Job scheduled actions
  - [x] Refactor VM scheduled actions to use this new resource and new Scheduled Action Manager
- [x] Java api
- [x] Go api
- [ ] Sunstone
- [x] Tests
- [x] Documentation

Remaining issues:
- [x] Conflict Backup Job and Single backups. Potentially, this can break backups (eg. increments save in different places or different backup types full will break increment). Proposal: Only let one way to do backups. i.e. VMs can be only of one backupjob id. A VM cannot join a backup job if an incremental chain is active.
- [x] Store Backup Job ID Image backup and VM.
- [x] BackupJob template update (BackupJob::parse())  shoud delete SCHED_ACTION attribute
- [x] Relative action times, are not supported for BJ, we should set set origin=0.
- [x] Template is append mode, so we cannot delete attributes. Proposal: This conflicts with the update somehow...
- [x] Update Restic Drivers to use BACKUP_JOB_ID
- [x] Review tests (java is failing?)
- [x] Run memory sanitizer
- [x] Documentation
  - [x] Update [table](https://docs.opennebula.io/6.6/management_and_operations/vm_management/vm_instances.html#relative-actions)
  - [x] Replace references to update-chart, delete-chart
