### ISSUE TITLE
[FSunstone] Schedule actions section on vm template

### ISSUE THREAD

**Issue by dcarracedo** [OpenNebula/one#6516]
**Description**
Issues on the Scheduled action section of the vm template:

**Issue 1**:
Sched action relative: If you try to update a schedule action that is of relative type, there is an error so the user cannot do this action.
[Screencast from 26-02-24 12:11:31.webm](https://github.com/OpenNebula/one/assets/134921994/2c4b5311-037a-4465-b9f8-305332923965)

**To Reproduce**

1. Create a template with a schedule action of relative type.
2. Update the template.
3. Go to Schedule action tab
4. Edit the scheduled action and click Accept.
5. Nothing happens and the form is not closed.

**Expected behavior**
That the scheduled action is updated without problems.

**Issue 2**:
Sched action default type: Mark as default the One time action.
![image](https://github.com/OpenNebula/one/assets/134921994/79ce2dbc-2785-44d2-b62e-acce734d7ed5)

**To Reproduce**
1. Create a template with a schedule action of relative type.
2. Go to Schedule action tab
3. Click on Add action button

**Expected behavior**
That the One time option is selected by default.
![image](https://github.com/OpenNebula/one/assets/134921994/e0a9cca4-ac6a-49c7-830d-cb07d4d8f010)

**Issue 3**:
Sched daily: If you select Daily, when you submit the form, there is an error about DAYS has to be an empty value. That’s because when you select Daily, DAYS has to be “0,1,2,3,4,5,6” (all days).
[Screencast from 26-02-24 12:19:13.webm](https://github.com/OpenNebula/one/assets/134921994/677f83c5-081c-49eb-ab40-2c3558ae9111)

**To Reproduce**
1. Create a template with a schedule action of relative type.
2. Go to Schedule action tab
3. Click on Add action button
4. Select a perioridic action with Daily as Granularity of the action.
5. Click accept and update the template.

**Expected behavior**
That there is no error when a template is updated or created with this type of scheduled action.

**Issue 4**:
Repetitions: Number of repetitions have to be mandatory if users select repetitions on end type value.

**To Reproduce**
1. Create a template with a schedule action of relative type.
2. Go to Schedule action tab
3. Click on Add action button
4. Select as end type Repetitions
5. Accept without add any number as repetitions.

**Expected behavior**
That if the user wants repetitions, he should add the number of repetitions mandatory.

**Issue 5**:
Time on periodic type: The field time on a periodic action it's the start time of the action, so change the name from "Time" to "Start time" (be careful because it's only on periodic action and this field is used in all the types of scheduled actions).
![image](https://github.com/OpenNebula/one/assets/134921994/41c16c53-a68e-45ce-9025-84a037aeee7b)

**To Reproduce**
1. Create a template with a schedule action of relative type.
2. Go to Schedule action tab
3. Click on Add action button
4. Select a perioridic action

**Expected behavior**
The label of the field is "Start time" in case of periodic schedule actions:
![image](https://github.com/OpenNebula/one/assets/134921994/0ad040d2-e89f-47c5-8d61-0902458eaf5a)

**Details**
 - Affected Component: FireEdge
 - Hypervisor: N/A
 - Version: 6.8

**Additional context**
There is a case to add on templateadvanced.func.spec.js tests:
- Develop a test to control the date component. Now, the tests type a string with the value of the time, but if you execute the test with npm run cypress:run the date component is launched, so the test could not add the time. We need a test that can manage the date component to select a date. IMPORTANT: Now the time field is ignored on the template check so change this ignore behavior after develop the test.

Also, test case "casePeriodic" in schedule.js templateAdvanced cases has to be uncommented after fix this issue.

**Tasks**
- [x] Issue 1
- [x] Issue 2
- [x] Issue 3
- [x] Issue 4
- [x] Issue 5
- [x] Testing date component
- [x] Uncomment case periodic schedule actions

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)
